// BA45F5260.h
//	This file contains the definition of registers for
//		Holtek BA45F5260 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.3, 4
// Do not modify manually.

#ifndef _BA45F5260_H_
#define _BA45F5260_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __pbp0 : 1;
	unsigned char : 7;
} __pbp_bits;

typedef union {
	__pbp_bits bits;
	__sfr_byte byte;
} __pbp_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char : 1;
	unsigned char __lvrf : 1;
	unsigned char : 5;
} __rstfc_bits;

typedef union {
	__rstfc_bits bits;
	__sfr_byte byte;
} __rstfc_type;

typedef struct {
	unsigned char __fsiden : 1;
	unsigned char __fhiden : 1;
	unsigned char __fss : 1;
	unsigned char __fhs : 1;
	unsigned char : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __scc_bits;

typedef union {
	__scc_bits bits;
	__sfr_byte byte;
} __scc_type;

typedef struct {
	unsigned char __hircen : 1;
	unsigned char __hircf : 1;
	unsigned char __hirc0 : 1;
	unsigned char __hirc1 : 1;
	unsigned char : 4;
} __hircc_bits;

typedef union {
	__hircc_bits bits;
	__sfr_byte byte;
} __hircc_type;

typedef struct {
	unsigned char __hxten : 1;
	unsigned char __hxtf : 1;
	unsigned char __hxtm : 1;
	unsigned char : 5;
} __hxtc_bits;

typedef union {
	__hxtc_bits bits;
	__sfr_byte byte;
} __hxtc_type;

typedef struct {
	unsigned char __lxten : 1;
	unsigned char __lxtf : 1;
	unsigned char __lxtsp : 1;
	unsigned char : 5;
} __lxtc_bits;

typedef union {
	__lxtc_bits bits;
	__sfr_byte byte;
} __lxtc_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char __pb4 : 1;
	unsigned char __pb5 : 1;
	unsigned char __pb6 : 1;
	unsigned char __pb7 : 1;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char __pbc4 : 1;
	unsigned char __pbc5 : 1;
	unsigned char __pbc6 : 1;
	unsigned char __pbc7 : 1;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char __pbpu4 : 1;
	unsigned char __pbpu5 : 1;
	unsigned char __pbpu6 : 1;
	unsigned char __pbpu7 : 1;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char : 2;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char : 2;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char : 2;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char __pd3 : 1;
	unsigned char : 4;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char __pdc3 : 1;
	unsigned char : 4;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char __pdpu3 : 1;
	unsigned char : 4;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __sds0 : 1;
	unsigned char __sds1 : 1;
	unsigned char __sds2 : 1;
	unsigned char __sds3 : 1;
	unsigned char __sds4 : 1;
	unsigned char __sds5 : 1;
	unsigned char __sds6 : 1;
	unsigned char : 1;
} __sdsw_bits;

typedef union {
	__sdsw_bits bits;
	__sfr_byte byte;
} __sdsw_type;

typedef struct {
	unsigned char __sda0pga0 : 1;
	unsigned char __sda0pga1 : 1;
	unsigned char __sda0pga2 : 1;
	unsigned char __sda0pga3 : 1;
	unsigned char __sda0pga4 : 1;
	unsigned char __sda0pga5 : 1;
	unsigned char : 2;
} __sdpgac0_bits;

typedef union {
	__sdpgac0_bits bits;
	__sfr_byte byte;
} __sdpgac0_type;

typedef struct {
	unsigned char __sda1pga0 : 1;
	unsigned char __sda1pga1 : 1;
	unsigned char __sda1pga2 : 1;
	unsigned char __sda1pga3 : 1;
	unsigned char __sda1pga4 : 1;
	unsigned char __sda1pga5 : 1;
	unsigned char __sda1pga6 : 1;
	unsigned char __sda1pga7 : 1;
} __sdpgac1_bits;

typedef union {
	__sdpgac1_bits bits;
	__sfr_byte byte;
} __sdpgac1_type;

typedef struct {
	unsigned char __sda0bw0 : 1;
	unsigned char __sda0bw1 : 1;
	unsigned char : 3;
	unsigned char __sda0o : 1;
	unsigned char __sda0en : 1;
	unsigned char : 1;
} __sda0c_bits;

typedef union {
	__sda0c_bits bits;
	__sfr_byte byte;
} __sda0c_type;

typedef struct {
	unsigned char __sda0of0 : 1;
	unsigned char __sda0of1 : 1;
	unsigned char __sda0of2 : 1;
	unsigned char __sda0of3 : 1;
	unsigned char __sda0of4 : 1;
	unsigned char __sda0of5 : 1;
	unsigned char __sda0rsp : 1;
	unsigned char __sda0ofm : 1;
} __sda0vos_bits;

typedef union {
	__sda0vos_bits bits;
	__sfr_byte byte;
} __sda0vos_type;

typedef struct {
	unsigned char __sda1bw0 : 1;
	unsigned char __sda1bw1 : 1;
	unsigned char : 3;
	unsigned char __sda1o : 1;
	unsigned char __sda1en : 1;
	unsigned char : 1;
} __sda1c_bits;

typedef union {
	__sda1c_bits bits;
	__sfr_byte byte;
} __sda1c_type;

typedef struct {
	unsigned char __sda1of0 : 1;
	unsigned char __sda1of1 : 1;
	unsigned char __sda1of2 : 1;
	unsigned char __sda1of3 : 1;
	unsigned char __sda1of4 : 1;
	unsigned char __sda1of5 : 1;
	unsigned char __sda1rsp : 1;
	unsigned char __sda1ofm : 1;
} __sda1vos_bits;

typedef union {
	__sda1vos_bits bits;
	__sfr_byte byte;
} __sda1vos_type;

typedef struct {
	unsigned char __sacs0 : 1;
	unsigned char __sacs1 : 1;
	unsigned char __sacs2 : 1;
	unsigned char __sacs3 : 1;
	unsigned char __adrfs : 1;
	unsigned char __adcen : 1;
	unsigned char __adbz : 1;
	unsigned char __start : 1;
} __sadc0_bits;

typedef union {
	__sadc0_bits bits;
	__sfr_byte byte;
} __sadc0_type;

typedef struct {
	unsigned char __sacks0 : 1;
	unsigned char __sacks1 : 1;
	unsigned char __sacks2 : 1;
	unsigned char __savrs0 : 1;
	unsigned char __savrs1 : 1;
	unsigned char __sains0 : 1;
	unsigned char __sains1 : 1;
	unsigned char __sains2 : 1;
} __sadc1_bits;

typedef union {
	__sadc1_bits bits;
	__sfr_byte byte;
} __sadc1_type;

typedef struct {
	unsigned char __tsen : 1;
	unsigned char __g5xen : 1;
	unsigned char : 6;
} __sadc2_bits;

typedef union {
	__sadc2_bits bits;
	__sfr_byte byte;
} __sadc2_type;

typedef struct {
	unsigned char __plts0 : 1;
	unsigned char __plts1 : 1;
	unsigned char __plts2 : 1;
	unsigned char : 5;
} __pltsw_bits;

typedef union {
	__pltsw_bits bits;
	__sfr_byte byte;
} __pltsw_type;

typedef struct {
	unsigned char __pltdac0en : 1;
	unsigned char __pltdac1en : 1;
	unsigned char __pltdac2en : 1;
	unsigned char : 5;
} __pltdacc_bits;

typedef union {
	__pltdacc_bits bits;
	__sfr_byte byte;
} __pltdacc_type;

typedef struct {
	unsigned char __pltc0is0 : 1;
	unsigned char __pltc0is1 : 1;
	unsigned char __pltc0deb0 : 1;
	unsigned char __pltc0deb1 : 1;
	unsigned char : 1;
	unsigned char __pltc0o : 1;
	unsigned char __pltc0en : 1;
	unsigned char __pltc0out : 1;
} __pltc0c_bits;

typedef union {
	__pltc0c_bits bits;
	__sfr_byte byte;
} __pltc0c_type;

typedef struct {
	unsigned char __pltc0of0 : 1;
	unsigned char __pltc0of1 : 1;
	unsigned char __pltc0of2 : 1;
	unsigned char __pltc0of3 : 1;
	unsigned char __pltc0of4 : 1;
	unsigned char __pltc0rsp : 1;
	unsigned char __pltc0ofm : 1;
	unsigned char : 1;
} __pltc0vos_bits;

typedef union {
	__pltc0vos_bits bits;
	__sfr_byte byte;
} __pltc0vos_type;

typedef struct {
	unsigned char __pltc1is0 : 1;
	unsigned char __pltc1is1 : 1;
	unsigned char __pltc1deb0 : 1;
	unsigned char __pltc1deb1 : 1;
	unsigned char : 1;
	unsigned char __pltc1o : 1;
	unsigned char __pltc1en : 1;
	unsigned char __pltc1out : 1;
} __pltc1c_bits;

typedef union {
	__pltc1c_bits bits;
	__sfr_byte byte;
} __pltc1c_type;

typedef struct {
	unsigned char __pltc1of0 : 1;
	unsigned char __pltc1of1 : 1;
	unsigned char __pltc1of2 : 1;
	unsigned char __pltc1of3 : 1;
	unsigned char __pltc1of4 : 1;
	unsigned char __pltc1rsp : 1;
	unsigned char __pltc1ofm : 1;
	unsigned char : 1;
} __pltc1vos_bits;

typedef union {
	__pltc1vos_bits bits;
	__sfr_byte byte;
} __pltc1vos_type;

typedef struct {
	unsigned char __pltc0hys0 : 1;
	unsigned char __pltc0hys1 : 1;
	unsigned char __pltc1hys0 : 1;
	unsigned char __pltc1hys1 : 1;
	unsigned char __pltc0pol : 1;
	unsigned char __pltc1pol : 1;
	unsigned char __pltcxosw : 1;
	unsigned char : 1;
} __pltchyc_bits;

typedef union {
	__pltchyc_bits bits;
	__sfr_byte byte;
} __pltchyc_type;

typedef struct {
	unsigned char __pltabw : 1;
	unsigned char : 4;
	unsigned char __pltao : 1;
	unsigned char __pltaen : 1;
	unsigned char : 1;
} __pltac_bits;

typedef union {
	__pltac_bits bits;
	__sfr_byte byte;
} __pltac_type;

typedef struct {
	unsigned char __pltaof0 : 1;
	unsigned char __pltaof1 : 1;
	unsigned char __pltaof2 : 1;
	unsigned char __pltaof3 : 1;
	unsigned char __pltaof4 : 1;
	unsigned char __pltaof5 : 1;
	unsigned char __pltarsp : 1;
	unsigned char __pltaofm : 1;
} __pltavos_bits;

typedef union {
	__pltavos_bits bits;
	__sfr_byte byte;
} __pltavos_type;

typedef struct {
	unsigned char __eea0 : 1;
	unsigned char __eea1 : 1;
	unsigned char __eea2 : 1;
	unsigned char __eea3 : 1;
	unsigned char __eea4 : 1;
	unsigned char __eea5 : 1;
	unsigned char __eea6 : 1;
	unsigned char __eea7 : 1;
} __eea_bits;

typedef union {
	__eea_bits bits;
	__sfr_byte byte;
} __eea_type;

typedef struct {
	unsigned char __isgs0 : 1;
	unsigned char __isgs1 : 1;
	unsigned char : 5;
	unsigned char __isgen : 1;
} __isgenc_bits;

typedef union {
	__isgenc_bits bits;
	__sfr_byte byte;
} __isgenc_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char : 4;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __pltc0e : 1;
	unsigned char __int0e : 1;
	unsigned char __int1e : 1;
	unsigned char __pltc0f : 1;
	unsigned char __int0f : 1;
	unsigned char __int1f : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __sime : 1;
	unsigned char __lve : 1;
	unsigned char __mf0e : 1;
	unsigned char __mf1e : 1;
	unsigned char __simf : 1;
	unsigned char __lvf : 1;
	unsigned char __mf0f : 1;
	unsigned char __mf1f : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __mf2e : 1;
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __pltc1e : 1;
	unsigned char __mf2f : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __pltc1f : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __mf3e : 1;
	unsigned char __mf4e : 1;
	unsigned char __mf5e : 1;
	unsigned char : 1;
	unsigned char __mf3f : 1;
	unsigned char __mf4f : 1;
	unsigned char __mf5f : 1;
	unsigned char : 1;
} __intc3_bits;

typedef union {
	__intc3_bits bits;
	__sfr_byte byte;
} __intc3_type;

typedef struct {
	unsigned char __ade : 1;
	unsigned char __dee : 1;
	unsigned char : 2;
	unsigned char __adf : 1;
	unsigned char __def : 1;
	unsigned char : 2;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __ptm0pe : 1;
	unsigned char __ptm0ae : 1;
	unsigned char : 2;
	unsigned char __ptm0pf : 1;
	unsigned char __ptm0af : 1;
	unsigned char : 2;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __stm0pe : 1;
	unsigned char __stm0ae : 1;
	unsigned char : 2;
	unsigned char __stm0pf : 1;
	unsigned char __stm0af : 1;
	unsigned char : 2;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char __stm1pe : 1;
	unsigned char __stm1ae : 1;
	unsigned char __ur0e : 1;
	unsigned char : 1;
	unsigned char __stm1pf : 1;
	unsigned char __stm1af : 1;
	unsigned char __ur0f : 1;
	unsigned char : 1;
} __mfi3_bits;

typedef union {
	__mfi3_bits bits;
	__sfr_byte byte;
} __mfi3_type;

typedef struct {
	unsigned char __ptm1pe : 1;
	unsigned char __ptm1ae : 1;
	unsigned char __ur1e : 1;
	unsigned char : 1;
	unsigned char __ptm1pf : 1;
	unsigned char __ptm1af : 1;
	unsigned char __ur1f : 1;
	unsigned char : 1;
} __mfi4_bits;

typedef union {
	__mfi4_bits bits;
	__sfr_byte byte;
} __mfi4_type;

typedef struct {
	unsigned char __ptm2pe : 1;
	unsigned char __ptm2ae : 1;
	unsigned char : 2;
	unsigned char __ptm2pf : 1;
	unsigned char __ptm2af : 1;
	unsigned char : 2;
} __mfi5_bits;

typedef union {
	__mfi5_bits bits;
	__sfr_byte byte;
} __mfi5_type;

typedef struct {
	unsigned char __vbgren : 1;
	unsigned char : 7;
} __vbgrc_bits;

typedef union {
	__vbgrc_bits bits;
	__sfr_byte byte;
} __vbgrc_type;

typedef struct {
	unsigned char __ormc0 : 1;
	unsigned char __ormc1 : 1;
	unsigned char __ormc2 : 1;
	unsigned char __ormc3 : 1;
	unsigned char __ormc4 : 1;
	unsigned char __ormc5 : 1;
	unsigned char __ormc6 : 1;
	unsigned char __ormc7 : 1;
} __ormc_bits;

typedef union {
	__ormc_bits bits;
	__sfr_byte byte;
} __ormc_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char __vbgen : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __clksel0 : 1;
	unsigned char __clksel1 : 1;
	unsigned char : 6;
} __pscr_bits;

typedef union {
	__pscr_bits bits;
	__sfr_byte byte;
} __pscr_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tb0c_bits;

typedef union {
	__tb0c_bits bits;
	__sfr_byte byte;
} __tb0c_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tb1c_bits;

typedef union {
	__tb1c_bits bits;
	__sfr_byte byte;
} __tb1c_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char : 1;
	unsigned char __sima0 : 1;
	unsigned char __sima1 : 1;
	unsigned char __sima2 : 1;
	unsigned char __sima3 : 1;
	unsigned char __sima4 : 1;
	unsigned char __sima5 : 1;
	unsigned char __sima6 : 1;
} __sima_bits;

typedef union {
	__sima_bits bits;
	__sfr_byte byte;
} __sima_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __txif0 : 1;
	unsigned char __tidle0 : 1;
	unsigned char __rxif0 : 1;
	unsigned char __ridle0 : 1;
	unsigned char __oerr0 : 1;
	unsigned char __ferr0 : 1;
	unsigned char __nf0 : 1;
	unsigned char __perr0 : 1;
} __u0sr_bits;

typedef union {
	__u0sr_bits bits;
	__sfr_byte byte;
} __u0sr_type;

typedef struct {
	unsigned char __tx80 : 1;
	unsigned char __rx80 : 1;
	unsigned char __txbrk0 : 1;
	unsigned char __stops0 : 1;
	unsigned char __prt0 : 1;
	unsigned char __pren0 : 1;
	unsigned char __bno0 : 1;
	unsigned char __uarten0 : 1;
} __u0cr1_bits;

typedef union {
	__u0cr1_bits bits;
	__sfr_byte byte;
} __u0cr1_type;

typedef struct {
	unsigned char __teie0 : 1;
	unsigned char __tiie0 : 1;
	unsigned char __rie0 : 1;
	unsigned char __wake0 : 1;
	unsigned char __adden0 : 1;
	unsigned char __brgh0 : 1;
	unsigned char __rxen0 : 1;
	unsigned char __txen0 : 1;
} __u0cr2_bits;

typedef union {
	__u0cr2_bits bits;
	__sfr_byte byte;
} __u0cr2_type;

typedef struct {
	unsigned char __swm0 : 1;
	unsigned char : 7;
} __u0cr3_bits;

typedef union {
	__u0cr3_bits bits;
	__sfr_byte byte;
} __u0cr3_type;

typedef struct {
	unsigned char __st0rp0 : 1;
	unsigned char __st0rp1 : 1;
	unsigned char __st0rp2 : 1;
	unsigned char __st0on : 1;
	unsigned char __st0ck0 : 1;
	unsigned char __st0ck1 : 1;
	unsigned char __st0ck2 : 1;
	unsigned char __st0pau : 1;
} __stm0c0_bits;

typedef union {
	__stm0c0_bits bits;
	__sfr_byte byte;
} __stm0c0_type;

typedef struct {
	unsigned char __st0cclr : 1;
	unsigned char __st0dpx : 1;
	unsigned char __st0pol : 1;
	unsigned char __st0oc : 1;
	unsigned char __st0io0 : 1;
	unsigned char __st0io1 : 1;
	unsigned char __st0m0 : 1;
	unsigned char __st0m1 : 1;
} __stm0c1_bits;

typedef union {
	__stm0c1_bits bits;
	__sfr_byte byte;
} __stm0c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt0on : 1;
	unsigned char __pt0ck0 : 1;
	unsigned char __pt0ck1 : 1;
	unsigned char __pt0ck2 : 1;
	unsigned char __pt0pau : 1;
} __ptm0c0_bits;

typedef union {
	__ptm0c0_bits bits;
	__sfr_byte byte;
} __ptm0c0_type;

typedef struct {
	unsigned char __pt0cclr : 1;
	unsigned char __pt0capts : 1;
	unsigned char __pt0pol : 1;
	unsigned char __pt0oc : 1;
	unsigned char __pt0io0 : 1;
	unsigned char __pt0io1 : 1;
	unsigned char __pt0m0 : 1;
	unsigned char __pt0m1 : 1;
} __ptm0c1_bits;

typedef union {
	__ptm0c1_bits bits;
	__sfr_byte byte;
} __ptm0c1_type;

typedef struct {
	unsigned char __pt0vlf : 1;
	unsigned char __pt0tclr0 : 1;
	unsigned char __pt0tclr1 : 1;
	unsigned char : 5;
} __ptm0c2_bits;

typedef union {
	__ptm0c2_bits bits;
	__sfr_byte byte;
} __ptm0c2_type;

typedef struct {
	unsigned char __dacen : 1;
	unsigned char : 7;
} __dacc_bits;

typedef union {
	__dacc_bits bits;
	__sfr_byte byte;
} __dacc_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __clwb : 1;
	unsigned char : 7;
} __fc2_bits;

typedef union {
	__fc2_bits bits;
	__sfr_byte byte;
} __fc2_type;

typedef struct {
	unsigned char __fa0 : 1;
	unsigned char __fa1 : 1;
	unsigned char __fa2 : 1;
	unsigned char __fa3 : 1;
	unsigned char __fa4 : 1;
	unsigned char __fa5 : 1;
	unsigned char __fa6 : 1;
	unsigned char __fa7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __fa8 : 1;
	unsigned char __fa9 : 1;
	unsigned char __fa10 : 1;
	unsigned char __fa11 : 1;
	unsigned char __fa12 : 1;
	unsigned char __fa13 : 1;
	unsigned char : 2;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char __st1rp0 : 1;
	unsigned char __st1rp1 : 1;
	unsigned char __st1rp2 : 1;
	unsigned char __st1on : 1;
	unsigned char __st1ck0 : 1;
	unsigned char __st1ck1 : 1;
	unsigned char __st1ck2 : 1;
	unsigned char __st1pau : 1;
} __stm1c0_bits;

typedef union {
	__stm1c0_bits bits;
	__sfr_byte byte;
} __stm1c0_type;

typedef struct {
	unsigned char __st1cclr : 1;
	unsigned char __st1dpx : 1;
	unsigned char __st1pol : 1;
	unsigned char __st1oc : 1;
	unsigned char __st1io0 : 1;
	unsigned char __st1io1 : 1;
	unsigned char __st1m0 : 1;
	unsigned char __st1m1 : 1;
} __stm1c1_bits;

typedef union {
	__stm1c1_bits bits;
	__sfr_byte byte;
} __stm1c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt1on : 1;
	unsigned char __pt1ck0 : 1;
	unsigned char __pt1ck1 : 1;
	unsigned char __pt1ck2 : 1;
	unsigned char __pt1pau : 1;
} __ptm1c0_bits;

typedef union {
	__ptm1c0_bits bits;
	__sfr_byte byte;
} __ptm1c0_type;

typedef struct {
	unsigned char __pt1cclr : 1;
	unsigned char __pt1capts : 1;
	unsigned char __pt1pol : 1;
	unsigned char __pt1oc : 1;
	unsigned char __pt1io0 : 1;
	unsigned char __pt1io1 : 1;
	unsigned char __pt1m0 : 1;
	unsigned char __pt1m1 : 1;
} __ptm1c1_bits;

typedef union {
	__ptm1c1_bits bits;
	__sfr_byte byte;
} __ptm1c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt2on : 1;
	unsigned char __pt2ck0 : 1;
	unsigned char __pt2ck1 : 1;
	unsigned char __pt2ck2 : 1;
	unsigned char __pt2pau : 1;
} __ptm2c0_bits;

typedef union {
	__ptm2c0_bits bits;
	__sfr_byte byte;
} __ptm2c0_type;

typedef struct {
	unsigned char __pt2cclr : 1;
	unsigned char __pt2capts : 1;
	unsigned char __pt2pol : 1;
	unsigned char __pt2oc : 1;
	unsigned char __pt2io0 : 1;
	unsigned char __pt2io1 : 1;
	unsigned char __pt2m0 : 1;
	unsigned char __pt2m1 : 1;
} __ptm2c1_bits;

typedef union {
	__ptm2c1_bits bits;
	__sfr_byte byte;
} __ptm2c1_type;

typedef struct {
	unsigned char __sledc00 : 1;
	unsigned char __sledc01 : 1;
	unsigned char __sledc02 : 1;
	unsigned char __sledc03 : 1;
	unsigned char __sledc04 : 1;
	unsigned char __sledc05 : 1;
	unsigned char __sledc06 : 1;
	unsigned char __sledc07 : 1;
} __sledc0_bits;

typedef union {
	__sledc0_bits bits;
	__sfr_byte byte;
} __sledc0_type;

typedef struct {
	unsigned char __sledc10 : 1;
	unsigned char __sledc11 : 1;
	unsigned char __sledc12 : 1;
	unsigned char __sledc13 : 1;
	unsigned char __sledc14 : 1;
	unsigned char __sledc15 : 1;
	unsigned char : 2;
} __sledc1_bits;

typedef union {
	__sledc1_bits bits;
	__sfr_byte byte;
} __sledc1_type;

typedef struct {
	unsigned char __pmps00 : 1;
	unsigned char __pmps01 : 1;
	unsigned char __pmps02 : 1;
	unsigned char __pmps03 : 1;
	unsigned char __pmps04 : 1;
	unsigned char __pmps05 : 1;
	unsigned char __pmps06 : 1;
	unsigned char __pmps07 : 1;
} __pmps0_bits;

typedef union {
	__pmps0_bits bits;
	__sfr_byte byte;
} __pmps0_type;

typedef struct {
	unsigned char __pmps10 : 1;
	unsigned char __pmps11 : 1;
	unsigned char __pmps12 : 1;
	unsigned char __pmps13 : 1;
	unsigned char __pmps14 : 1;
	unsigned char __pmps15 : 1;
	unsigned char : 2;
} __pmps1_bits;

typedef union {
	__pmps1_bits bits;
	__sfr_byte byte;
} __pmps1_type;

typedef struct {
	unsigned char __txif1 : 1;
	unsigned char __tidle1 : 1;
	unsigned char __rxif1 : 1;
	unsigned char __ridle1 : 1;
	unsigned char __oerr1 : 1;
	unsigned char __ferr1 : 1;
	unsigned char __nf1 : 1;
	unsigned char __perr1 : 1;
} __u1sr_bits;

typedef union {
	__u1sr_bits bits;
	__sfr_byte byte;
} __u1sr_type;

typedef struct {
	unsigned char __tx81 : 1;
	unsigned char __rx81 : 1;
	unsigned char __txbrk1 : 1;
	unsigned char __stops1 : 1;
	unsigned char __prt1 : 1;
	unsigned char __pren1 : 1;
	unsigned char __bno1 : 1;
	unsigned char __uarten1 : 1;
} __u1cr1_bits;

typedef union {
	__u1cr1_bits bits;
	__sfr_byte byte;
} __u1cr1_type;

typedef struct {
	unsigned char __teie1 : 1;
	unsigned char __tiie1 : 1;
	unsigned char __rie1 : 1;
	unsigned char __wake1 : 1;
	unsigned char __adden1 : 1;
	unsigned char __brgh1 : 1;
	unsigned char __rxen1 : 1;
	unsigned char __txen1 : 1;
} __u1cr2_bits;

typedef union {
	__u1cr2_bits bits;
	__sfr_byte byte;
} __u1cr2_type;

typedef struct {
	unsigned char __swm1 : 1;
	unsigned char : 7;
} __u1cr3_bits;

typedef union {
	__u1cr3_bits bits;
	__sfr_byte byte;
} __u1cr3_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;

typedef struct {
	unsigned char __pas00 : 1;
	unsigned char __pas01 : 1;
	unsigned char __pas02 : 1;
	unsigned char __pas03 : 1;
	unsigned char __pas04 : 1;
	unsigned char __pas05 : 1;
	unsigned char __pas06 : 1;
	unsigned char __pas07 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char __pas10 : 1;
	unsigned char __pas11 : 1;
	unsigned char __pas12 : 1;
	unsigned char __pas13 : 1;
	unsigned char __pas14 : 1;
	unsigned char __pas15 : 1;
	unsigned char __pas16 : 1;
	unsigned char __pas17 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pbs00 : 1;
	unsigned char __pbs01 : 1;
	unsigned char __pbs02 : 1;
	unsigned char __pbs03 : 1;
	unsigned char __pbs04 : 1;
	unsigned char __pbs05 : 1;
	unsigned char __pbs06 : 1;
	unsigned char __pbs07 : 1;
} __pbs0_bits;

typedef union {
	__pbs0_bits bits;
	__sfr_byte byte;
} __pbs0_type;

typedef struct {
	unsigned char __pbs10 : 1;
	unsigned char __pbs11 : 1;
	unsigned char __pbs12 : 1;
	unsigned char __pbs13 : 1;
	unsigned char __pbs14 : 1;
	unsigned char __pbs15 : 1;
	unsigned char __pbs16 : 1;
	unsigned char __pbs17 : 1;
} __pbs1_bits;

typedef union {
	__pbs1_bits bits;
	__sfr_byte byte;
} __pbs1_type;

typedef struct {
	unsigned char __pcs00 : 1;
	unsigned char __pcs01 : 1;
	unsigned char __pcs02 : 1;
	unsigned char __pcs03 : 1;
	unsigned char __pcs04 : 1;
	unsigned char __pcs05 : 1;
	unsigned char __pcs06 : 1;
	unsigned char __pcs07 : 1;
} __pcs0_bits;

typedef union {
	__pcs0_bits bits;
	__sfr_byte byte;
} __pcs0_type;

typedef struct {
	unsigned char __pcs10 : 1;
	unsigned char __pcs11 : 1;
	unsigned char __pcs12 : 1;
	unsigned char __pcs13 : 1;
	unsigned char : 4;
} __pcs1_bits;

typedef union {
	__pcs1_bits bits;
	__sfr_byte byte;
} __pcs1_type;

typedef struct {
	unsigned char __pds00 : 1;
	unsigned char __pds01 : 1;
	unsigned char __pds02 : 1;
	unsigned char __pds03 : 1;
	unsigned char __pds04 : 1;
	unsigned char __pds05 : 1;
	unsigned char __pds06 : 1;
	unsigned char __pds07 : 1;
} __pds0_bits;

typedef union {
	__pds0_bits bits;
	__sfr_byte byte;
} __pds0_type;

typedef struct {
	unsigned char __ifs00 : 1;
	unsigned char __ifs01 : 1;
	unsigned char __ifs02 : 1;
	unsigned char __ifs03 : 1;
	unsigned char __ifs04 : 1;
	unsigned char __ifs05 : 1;
	unsigned char __ifs06 : 1;
	unsigned char __ifs07 : 1;
} __ifs0_bits;

typedef union {
	__ifs0_bits bits;
	__sfr_byte byte;
} __ifs0_type;

typedef struct {
	unsigned char __ifs10 : 1;
	unsigned char __ifs11 : 1;
	unsigned char __ifs12 : 1;
	unsigned char __ifs13 : 1;
	unsigned char __ifs14 : 1;
	unsigned char __ifs15 : 1;
	unsigned char : 2;
} __ifs1_bits;

typedef union {
	__ifs1_bits bits;
	__sfr_byte byte;
} __ifs1_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1l, 0x03);
DEFINE_SFR(__sfr_byte, __mp1h, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__sfr_byte, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__pbp_type, __pbp, 0x0b);
DEFINE_SFR(__sfr_byte, __mp2l, 0x0d);
DEFINE_SFR(__sfr_byte, __mp2h, 0x0e);
DEFINE_SFR(__rstfc_type, __rstfc, 0x0f);
DEFINE_SFR(__scc_type, __scc, 0x10);
DEFINE_SFR(__hircc_type, __hircc, 0x11);
DEFINE_SFR(__hxtc_type, __hxtc, 0x12);
DEFINE_SFR(__lxtc_type, __lxtc, 0x13);
DEFINE_SFR(__pa_type, __pa, 0x14);
DEFINE_SFR(__pac_type, __pac, 0x15);
DEFINE_SFR(__papu_type, __papu, 0x16);
DEFINE_SFR(__pawu_type, __pawu, 0x17);
DEFINE_SFR(__pb_type, __pb, 0x18);
DEFINE_SFR(__pbc_type, __pbc, 0x19);
DEFINE_SFR(__pbpu_type, __pbpu, 0x1a);
DEFINE_SFR(__pc_type, __pc, 0x1b);
DEFINE_SFR(__pcc_type, __pcc, 0x1c);
DEFINE_SFR(__pcpu_type, __pcpu, 0x1d);
DEFINE_SFR(__pd_type, __pd, 0x1e);
DEFINE_SFR(__pdc_type, __pdc, 0x1f);
DEFINE_SFR(__pdpu_type, __pdpu, 0x20);
DEFINE_SFR(__wdtc_type, __wdtc, 0x21);
DEFINE_SFR(__sdsw_type, __sdsw, 0x22);
DEFINE_SFR(__sdpgac0_type, __sdpgac0, 0x23);
DEFINE_SFR(__sdpgac1_type, __sdpgac1, 0x24);
DEFINE_SFR(__sda0c_type, __sda0c, 0x25);
DEFINE_SFR(__sda0vos_type, __sda0vos, 0x26);
DEFINE_SFR(__sda1c_type, __sda1c, 0x27);
DEFINE_SFR(__sda1vos_type, __sda1vos, 0x28);
DEFINE_SFR(__sadc0_type, __sadc0, 0x2a);
DEFINE_SFR(__sadc1_type, __sadc1, 0x2b);
DEFINE_SFR(__sadc2_type, __sadc2, 0x2c);
DEFINE_SFR(__sfr_byte, __sadoh, 0x2d);
DEFINE_SFR(__sfr_byte, __sadol, 0x2e);
DEFINE_SFR(__sfr_byte, __lmsadoh, 0x2f);
DEFINE_SFR(__sfr_byte, __lmsadol, 0x30);
DEFINE_SFR(__pltsw_type, __pltsw, 0x31);
DEFINE_SFR(__pltdacc_type, __pltdacc, 0x32);
DEFINE_SFR(__sfr_byte, __pltda0l, 0x33);
DEFINE_SFR(__sfr_byte, __pltda1l, 0x34);
DEFINE_SFR(__sfr_byte, __pltda2l, 0x35);
DEFINE_SFR(__pltc0c_type, __pltc0c, 0x36);
DEFINE_SFR(__pltc0vos_type, __pltc0vos, 0x37);
DEFINE_SFR(__pltc1c_type, __pltc1c, 0x38);
DEFINE_SFR(__pltc1vos_type, __pltc1vos, 0x39);
DEFINE_SFR(__pltchyc_type, __pltchyc, 0x3a);
DEFINE_SFR(__pltac_type, __pltac, 0x3b);
DEFINE_SFR(__pltavos_type, __pltavos, 0x3c);
DEFINE_SFR(__eea_type, __eea, 0x3d);
DEFINE_SFR(__sfr_byte, __eed, 0x3e);
DEFINE_SFR(__isgenc_type, __isgenc, 0x3f);
DEFINE_SFR(__sfr_byte, __isgdata0, 0x40);
DEFINE_SFR(__sfr_byte, __isgdata1, 0x41);
DEFINE_SFR(__integ_type, __integ, 0x42);
DEFINE_SFR(__intc0_type, __intc0, 0x43);
DEFINE_SFR(__intc1_type, __intc1, 0x44);
DEFINE_SFR(__intc2_type, __intc2, 0x45);
DEFINE_SFR(__intc3_type, __intc3, 0x46);
DEFINE_SFR(__mfi0_type, __mfi0, 0x47);
DEFINE_SFR(__mfi1_type, __mfi1, 0x48);
DEFINE_SFR(__mfi2_type, __mfi2, 0x49);
DEFINE_SFR(__mfi3_type, __mfi3, 0x4a);
DEFINE_SFR(__mfi4_type, __mfi4, 0x4b);
DEFINE_SFR(__mfi5_type, __mfi5, 0x4c);
DEFINE_SFR(__vbgrc_type, __vbgrc, 0x4d);
DEFINE_SFR(__ormc_type, __ormc, 0x4e);
DEFINE_SFR(__lvdc_type, __lvdc, 0x4f);
DEFINE_SFR(__pscr_type, __pscr, 0x50);
DEFINE_SFR(__tb0c_type, __tb0c, 0x51);
DEFINE_SFR(__tb1c_type, __tb1c, 0x52);
DEFINE_SFR(__simc0_type, __simc0, 0x53);
DEFINE_SFR(__simc1_type, __simc1, 0x54);
DEFINE_SFR(__sfr_byte, __simd, 0x55);
DEFINE_SFR(__sima_type, __sima, 0x56);
DEFINE_SFR(__simc2_type, __simc2, 0x56);
DEFINE_SFR(__simtoc_type, __simtoc, 0x57);
DEFINE_SFR(__u0sr_type, __u0sr, 0x59);
DEFINE_SFR(__u0cr1_type, __u0cr1, 0x5a);
DEFINE_SFR(__u0cr2_type, __u0cr2, 0x5b);
DEFINE_SFR(__u0cr3_type, __u0cr3, 0x5c);
DEFINE_SFR(__sfr_byte, __txr_rxr0, 0x5d);
DEFINE_SFR(__sfr_byte, __brg0, 0x5e);
DEFINE_SFR(__stm0c0_type, __stm0c0, 0x5f);
DEFINE_SFR(__stm0c1_type, __stm0c1, 0x60);
DEFINE_SFR(__sfr_byte, __stm0dl, 0x61);
DEFINE_SFR(__sfr_byte, __stm0dh, 0x62);
DEFINE_SFR(__sfr_byte, __stm0al, 0x63);
DEFINE_SFR(__sfr_byte, __stm0ah, 0x64);
DEFINE_SFR(__ptm0c0_type, __ptm0c0, 0x65);
DEFINE_SFR(__ptm0c1_type, __ptm0c1, 0x66);
DEFINE_SFR(__ptm0c2_type, __ptm0c2, 0x67);
DEFINE_SFR(__sfr_byte, __ptm0dl, 0x68);
DEFINE_SFR(__sfr_byte, __ptm0dh, 0x69);
DEFINE_SFR(__sfr_byte, __ptm0al, 0x6a);
DEFINE_SFR(__sfr_byte, __ptm0ah, 0x6b);
DEFINE_SFR(__sfr_byte, __ptm0bl, 0x6c);
DEFINE_SFR(__sfr_byte, __ptm0bh, 0x6d);
DEFINE_SFR(__sfr_byte, __ptm0rpl, 0x6e);
DEFINE_SFR(__sfr_byte, __ptm0rph, 0x6f);
DEFINE_SFR(__sfr_byte, __dah, 0x70);
DEFINE_SFR(__sfr_byte, __dal, 0x71);
DEFINE_SFR(__dacc_type, __dacc, 0x72);
DEFINE_SFR(__fc0_type, __fc0, 0x73);
DEFINE_SFR(__sfr_byte, __fc1, 0x74);
DEFINE_SFR(__fc2_type, __fc2, 0x75);
DEFINE_SFR(__farl_type, __farl, 0x76);
DEFINE_SFR(__farh_type, __farh, 0x77);
DEFINE_SFR(__sfr_byte, __fd0l, 0x78);
DEFINE_SFR(__sfr_byte, __fd0h, 0x79);
DEFINE_SFR(__sfr_byte, __fd1l, 0x7a);
DEFINE_SFR(__sfr_byte, __fd1h, 0x7b);
DEFINE_SFR(__sfr_byte, __fd2l, 0x7c);
DEFINE_SFR(__sfr_byte, __fd2h, 0x7d);
DEFINE_SFR(__sfr_byte, __fd3l, 0x7e);
DEFINE_SFR(__sfr_byte, __fd3h, 0x7f);
DEFINE_SFR(__stm1c0_type, __stm1c0, 0x11a);
DEFINE_SFR(__stm1c1_type, __stm1c1, 0x11b);
DEFINE_SFR(__sfr_byte, __stm1dl, 0x11c);
DEFINE_SFR(__sfr_byte, __stm1dh, 0x11d);
DEFINE_SFR(__sfr_byte, __stm1al, 0x11e);
DEFINE_SFR(__sfr_byte, __stm1ah, 0x11f);
DEFINE_SFR(__ptm1c0_type, __ptm1c0, 0x121);
DEFINE_SFR(__ptm1c1_type, __ptm1c1, 0x122);
DEFINE_SFR(__sfr_byte, __ptm1dl, 0x123);
DEFINE_SFR(__sfr_byte, __ptm1dh, 0x124);
DEFINE_SFR(__sfr_byte, __ptm1al, 0x125);
DEFINE_SFR(__sfr_byte, __ptm1ah, 0x126);
DEFINE_SFR(__sfr_byte, __ptm1rpl, 0x127);
DEFINE_SFR(__sfr_byte, __ptm1rph, 0x128);
DEFINE_SFR(__ptm2c0_type, __ptm2c0, 0x12a);
DEFINE_SFR(__ptm2c1_type, __ptm2c1, 0x12b);
DEFINE_SFR(__sfr_byte, __ptm2dl, 0x12c);
DEFINE_SFR(__sfr_byte, __ptm2dh, 0x12d);
DEFINE_SFR(__sfr_byte, __ptm2al, 0x12e);
DEFINE_SFR(__sfr_byte, __ptm2ah, 0x12f);
DEFINE_SFR(__sfr_byte, __ptm2rpl, 0x130);
DEFINE_SFR(__sfr_byte, __ptm2rph, 0x131);
DEFINE_SFR(__sledc0_type, __sledc0, 0x133);
DEFINE_SFR(__sledc1_type, __sledc1, 0x134);
DEFINE_SFR(__pmps0_type, __pmps0, 0x136);
DEFINE_SFR(__pmps1_type, __pmps1, 0x137);
DEFINE_SFR(__u1sr_type, __u1sr, 0x139);
DEFINE_SFR(__u1cr1_type, __u1cr1, 0x13a);
DEFINE_SFR(__u1cr2_type, __u1cr2, 0x13b);
DEFINE_SFR(__u1cr3_type, __u1cr3, 0x13c);
DEFINE_SFR(__sfr_byte, __txr_rxr1, 0x13d);
DEFINE_SFR(__sfr_byte, __brg1, 0x13e);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__pas0_type, __pas0, 0x142);
DEFINE_SFR(__pas1_type, __pas1, 0x143);
DEFINE_SFR(__pbs0_type, __pbs0, 0x144);
DEFINE_SFR(__pbs1_type, __pbs1, 0x145);
DEFINE_SFR(__pcs0_type, __pcs0, 0x146);
DEFINE_SFR(__pcs1_type, __pcs1, 0x147);
DEFINE_SFR(__pds0_type, __pds0, 0x148);
DEFINE_SFR(__ifs0_type, __ifs0, 0x14a);
DEFINE_SFR(__ifs1_type, __ifs1, 0x14b);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);
DEFINE_SFR(__sfr_byte, __iar2, 0x0C);

#define _iar0     __iar0
#define _iar1     __iar1
#define _iar2     __iar2
#define _mp0      __mp0
#define _mp1l     __mp1l
#define _mp1h     __mp1h
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _tbhp     __tbhp
#define _status   __status.byte
#define _pbp      __pbp.byte
#define _mp2l     __mp2l
#define _mp2h     __mp2h
#define _rstfc    __rstfc.byte
#define _scc      __scc.byte
#define _hircc    __hircc.byte
#define _hxtc     __hxtc.byte
#define _lxtc     __lxtc.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _papu     __papu.byte
#define _pawu     __pawu.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pbpu     __pbpu.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pcpu     __pcpu.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _pdpu     __pdpu.byte
#define _wdtc     __wdtc.byte
#define _sdsw     __sdsw.byte
#define _sdpgac0  __sdpgac0.byte
#define _sdpgac1  __sdpgac1.byte
#define _sda0c    __sda0c.byte
#define _sda0vos  __sda0vos.byte
#define _sda1c    __sda1c.byte
#define _sda1vos  __sda1vos.byte
#define _sadc0    __sadc0.byte
#define _sadc1    __sadc1.byte
#define _sadc2    __sadc2.byte
#define _sadoh    __sadoh
#define _sadol    __sadol
#define _lmsadoh  __lmsadoh
#define _lmsadol  __lmsadol
#define _pltsw    __pltsw.byte
#define _pltdacc  __pltdacc.byte
#define _pltda0l  __pltda0l
#define _pltda1l  __pltda1l
#define _pltda2l  __pltda2l
#define _pltc0c   __pltc0c.byte
#define _pltc0vos __pltc0vos.byte
#define _pltc1c   __pltc1c.byte
#define _pltc1vos __pltc1vos.byte
#define _pltchyc  __pltchyc.byte
#define _pltac    __pltac.byte
#define _pltavos  __pltavos.byte
#define _eea      __eea.byte
#define _eed      __eed
#define _isgenc   __isgenc.byte
#define _isgdata0 __isgdata0
#define _isgdata1 __isgdata1
#define _integ    __integ.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _intc3    __intc3.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _mfi3     __mfi3.byte
#define _mfi4     __mfi4.byte
#define _mfi5     __mfi5.byte
#define _vbgrc    __vbgrc.byte
#define _ormc     __ormc.byte
#define _lvdc     __lvdc.byte
#define _pscr     __pscr.byte
#define _tb0c     __tb0c.byte
#define _tb1c     __tb1c.byte
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simd     __simd
#define _sima     __sima.byte
#define _simc2    __simc2.byte
#define _simtoc   __simtoc.byte
#define _u0sr     __u0sr.byte
#define _u0cr1    __u0cr1.byte
#define _u0cr2    __u0cr2.byte
#define _u0cr3    __u0cr3.byte
#define _txr_rxr0 __txr_rxr0
#define _brg0     __brg0
#define _stm0c0   __stm0c0.byte
#define _stm0c1   __stm0c1.byte
#define _stm0dl   __stm0dl
#define _stm0dh   __stm0dh
#define _stm0al   __stm0al
#define _stm0ah   __stm0ah
#define _ptm0c0   __ptm0c0.byte
#define _ptm0c1   __ptm0c1.byte
#define _ptm0c2   __ptm0c2.byte
#define _ptm0dl   __ptm0dl
#define _ptm0dh   __ptm0dh
#define _ptm0al   __ptm0al
#define _ptm0ah   __ptm0ah
#define _ptm0bl   __ptm0bl
#define _ptm0bh   __ptm0bh
#define _ptm0rpl  __ptm0rpl
#define _ptm0rph  __ptm0rph
#define _dah      __dah
#define _dal      __dal
#define _dacc     __dacc.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _fc2      __fc2.byte
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _stm1c0   __stm1c0.byte
#define _stm1c1   __stm1c1.byte
#define _stm1dl   __stm1dl
#define _stm1dh   __stm1dh
#define _stm1al   __stm1al
#define _stm1ah   __stm1ah
#define _ptm1c0   __ptm1c0.byte
#define _ptm1c1   __ptm1c1.byte
#define _ptm1dl   __ptm1dl
#define _ptm1dh   __ptm1dh
#define _ptm1al   __ptm1al
#define _ptm1ah   __ptm1ah
#define _ptm1rpl  __ptm1rpl
#define _ptm1rph  __ptm1rph
#define _ptm2c0   __ptm2c0.byte
#define _ptm2c1   __ptm2c1.byte
#define _ptm2dl   __ptm2dl
#define _ptm2dh   __ptm2dh
#define _ptm2al   __ptm2al
#define _ptm2ah   __ptm2ah
#define _ptm2rpl  __ptm2rpl
#define _ptm2rph  __ptm2rph
#define _sledc0   __sledc0.byte
#define _sledc1   __sledc1.byte
#define _pmps0    __pmps0.byte
#define _pmps1    __pmps1.byte
#define _u1sr     __u1sr.byte
#define _u1cr1    __u1cr1.byte
#define _u1cr2    __u1cr2.byte
#define _u1cr3    __u1cr3.byte
#define _txr_rxr1 __txr_rxr1
#define _brg1     __brg1
#define _eec      __eec.byte
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pbs0     __pbs0.byte
#define _pbs1     __pbs1.byte
#define _pcs0     __pcs0.byte
#define _pcs1     __pcs1.byte
#define _pds0     __pds0.byte
#define _ifs0     __ifs0.byte
#define _ifs1     __ifs1.byte

#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _pbp0            __pbp.bits.__pbp0
#define _wrf      __rstfc.bits.__wrf
#define _lvrf     __rstfc.bits.__lvrf
#define _fsiden   __scc.bits.__fsiden
#define _fhiden   __scc.bits.__fhiden
#define _fss      __scc.bits.__fss
#define _fhs      __scc.bits.__fhs
#define _cks0     __scc.bits.__cks0
#define _cks1     __scc.bits.__cks1
#define _cks2     __scc.bits.__cks2
#define _hircen   __hircc.bits.__hircen
#define _hircf    __hircc.bits.__hircf
#define _hirc0    __hircc.bits.__hirc0
#define _hirc1    __hircc.bits.__hirc1
#define _hxten    __hxtc.bits.__hxten
#define _hxtf     __hxtc.bits.__hxtf
#define _hxtm     __hxtc.bits.__hxtm
#define _lxten    __lxtc.bits.__lxten
#define _lxtf     __lxtc.bits.__lxtf
#define _lxtsp    __lxtc.bits.__lxtsp
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pb4      __pb.bits.__pb4
#define _pb5      __pb.bits.__pb5
#define _pb6      __pb.bits.__pb6
#define _pb7      __pb.bits.__pb7
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbc4     __pbc.bits.__pbc4
#define _pbc5     __pbc.bits.__pbc5
#define _pbc6     __pbc.bits.__pbc6
#define _pbc7     __pbc.bits.__pbc7
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pbpu4    __pbpu.bits.__pbpu4
#define _pbpu5    __pbpu.bits.__pbpu5
#define _pbpu6    __pbpu.bits.__pbpu6
#define _pbpu7    __pbpu.bits.__pbpu7
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pd3      __pd.bits.__pd3
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _pdc3     __pdc.bits.__pdc3
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pdpu3    __pdpu.bits.__pdpu3
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _sds0     __sdsw.bits.__sds0
#define _sds1     __sdsw.bits.__sds1
#define _sds2     __sdsw.bits.__sds2
#define _sds3     __sdsw.bits.__sds3
#define _sds4     __sdsw.bits.__sds4
#define _sds5     __sdsw.bits.__sds5
#define _sds6     __sdsw.bits.__sds6
#define _sda0pga0 __sdpgac0.bits.__sda0pga0
#define _sda0pga1 __sdpgac0.bits.__sda0pga1
#define _sda0pga2 __sdpgac0.bits.__sda0pga2
#define _sda0pga3 __sdpgac0.bits.__sda0pga3
#define _sda0pga4 __sdpgac0.bits.__sda0pga4
#define _sda0pga5 __sdpgac0.bits.__sda0pga5
#define _sda1pga0 __sdpgac1.bits.__sda1pga0
#define _sda1pga1 __sdpgac1.bits.__sda1pga1
#define _sda1pga2 __sdpgac1.bits.__sda1pga2
#define _sda1pga3 __sdpgac1.bits.__sda1pga3
#define _sda1pga4 __sdpgac1.bits.__sda1pga4
#define _sda1pga5 __sdpgac1.bits.__sda1pga5
#define _sda1pga6 __sdpgac1.bits.__sda1pga6
#define _sda1pga7 __sdpgac1.bits.__sda1pga7
#define _sda0bw0  __sda0c.bits.__sda0bw0
#define _sda0bw1  __sda0c.bits.__sda0bw1
#define _sda0o    __sda0c.bits.__sda0o
#define _sda0en   __sda0c.bits.__sda0en
#define _sda0of0  __sda0vos.bits.__sda0of0
#define _sda0of1  __sda0vos.bits.__sda0of1
#define _sda0of2  __sda0vos.bits.__sda0of2
#define _sda0of3  __sda0vos.bits.__sda0of3
#define _sda0of4  __sda0vos.bits.__sda0of4
#define _sda0of5  __sda0vos.bits.__sda0of5
#define _sda0rsp  __sda0vos.bits.__sda0rsp
#define _sda0ofm  __sda0vos.bits.__sda0ofm
#define _sda1bw0  __sda1c.bits.__sda1bw0
#define _sda1bw1  __sda1c.bits.__sda1bw1
#define _sda1o    __sda1c.bits.__sda1o
#define _sda1en   __sda1c.bits.__sda1en
#define _sda1of0  __sda1vos.bits.__sda1of0
#define _sda1of1  __sda1vos.bits.__sda1of1
#define _sda1of2  __sda1vos.bits.__sda1of2
#define _sda1of3  __sda1vos.bits.__sda1of3
#define _sda1of4  __sda1vos.bits.__sda1of4
#define _sda1of5  __sda1vos.bits.__sda1of5
#define _sda1rsp  __sda1vos.bits.__sda1rsp
#define _sda1ofm  __sda1vos.bits.__sda1ofm
#define _sacs0    __sadc0.bits.__sacs0
#define _sacs1    __sadc0.bits.__sacs1
#define _sacs2    __sadc0.bits.__sacs2
#define _sacs3    __sadc0.bits.__sacs3
#define _adrfs    __sadc0.bits.__adrfs
#define _adcen    __sadc0.bits.__adcen
#define _adbz     __sadc0.bits.__adbz
#define _start    __sadc0.bits.__start
#define _sacks0   __sadc1.bits.__sacks0
#define _sacks1   __sadc1.bits.__sacks1
#define _sacks2   __sadc1.bits.__sacks2
#define _savrs0   __sadc1.bits.__savrs0
#define _savrs1   __sadc1.bits.__savrs1
#define _sains0   __sadc1.bits.__sains0
#define _sains1   __sadc1.bits.__sains1
#define _sains2   __sadc1.bits.__sains2
#define _tsen     __sadc2.bits.__tsen
#define _g5xen    __sadc2.bits.__g5xen
#define _plts0    __pltsw.bits.__plts0
#define _plts1    __pltsw.bits.__plts1
#define _plts2    __pltsw.bits.__plts2
#define _pltdac0en __pltdacc.bits.__pltdac0en
#define _pltdac1en __pltdacc.bits.__pltdac1en
#define _pltdac2en __pltdacc.bits.__pltdac2en
#define _pltc0is0 __pltc0c.bits.__pltc0is0
#define _pltc0is1 __pltc0c.bits.__pltc0is1
#define _pltc0deb0 __pltc0c.bits.__pltc0deb0
#define _pltc0deb1 __pltc0c.bits.__pltc0deb1
#define _pltc0o   __pltc0c.bits.__pltc0o
#define _pltc0en  __pltc0c.bits.__pltc0en
#define _pltc0out __pltc0c.bits.__pltc0out
#define _pltc0of0 __pltc0vos.bits.__pltc0of0
#define _pltc0of1 __pltc0vos.bits.__pltc0of1
#define _pltc0of2 __pltc0vos.bits.__pltc0of2
#define _pltc0of3 __pltc0vos.bits.__pltc0of3
#define _pltc0of4 __pltc0vos.bits.__pltc0of4
#define _pltc0rsp __pltc0vos.bits.__pltc0rsp
#define _pltc0ofm __pltc0vos.bits.__pltc0ofm
#define _pltc1is0 __pltc1c.bits.__pltc1is0
#define _pltc1is1 __pltc1c.bits.__pltc1is1
#define _pltc1deb0 __pltc1c.bits.__pltc1deb0
#define _pltc1deb1 __pltc1c.bits.__pltc1deb1
#define _pltc1o   __pltc1c.bits.__pltc1o
#define _pltc1en  __pltc1c.bits.__pltc1en
#define _pltc1out __pltc1c.bits.__pltc1out
#define _pltc1of0 __pltc1vos.bits.__pltc1of0
#define _pltc1of1 __pltc1vos.bits.__pltc1of1
#define _pltc1of2 __pltc1vos.bits.__pltc1of2
#define _pltc1of3 __pltc1vos.bits.__pltc1of3
#define _pltc1of4 __pltc1vos.bits.__pltc1of4
#define _pltc1rsp __pltc1vos.bits.__pltc1rsp
#define _pltc1ofm __pltc1vos.bits.__pltc1ofm
#define _pltc0hys0 __pltchyc.bits.__pltc0hys0
#define _pltc0hys1 __pltchyc.bits.__pltc0hys1
#define _pltc1hys0 __pltchyc.bits.__pltc1hys0
#define _pltc1hys1 __pltchyc.bits.__pltc1hys1
#define _pltc0pol __pltchyc.bits.__pltc0pol
#define _pltc1pol __pltchyc.bits.__pltc1pol
#define _pltcxosw __pltchyc.bits.__pltcxosw
#define _pltabw   __pltac.bits.__pltabw
#define _pltao    __pltac.bits.__pltao
#define _pltaen   __pltac.bits.__pltaen
#define _pltaof0  __pltavos.bits.__pltaof0
#define _pltaof1  __pltavos.bits.__pltaof1
#define _pltaof2  __pltavos.bits.__pltaof2
#define _pltaof3  __pltavos.bits.__pltaof3
#define _pltaof4  __pltavos.bits.__pltaof4
#define _pltaof5  __pltavos.bits.__pltaof5
#define _pltarsp  __pltavos.bits.__pltarsp
#define _pltaofm  __pltavos.bits.__pltaofm
#define _eea0     __eea.bits.__eea0
#define _eea1     __eea.bits.__eea1
#define _eea2     __eea.bits.__eea2
#define _eea3     __eea.bits.__eea3
#define _eea4     __eea.bits.__eea4
#define _eea5     __eea.bits.__eea5
#define _eea6     __eea.bits.__eea6
#define _eea7     __eea.bits.__eea7
#define _isgs0    __isgenc.bits.__isgs0
#define _isgs1    __isgenc.bits.__isgs1
#define _isgen    __isgenc.bits.__isgen
#define _int0s0   __integ.bits.__int0s0
#define _int0s1   __integ.bits.__int0s1
#define _int1s0   __integ.bits.__int1s0
#define _int1s1   __integ.bits.__int1s1
#define _emi      __intc0.bits.__emi
#define _pltc0e   __intc0.bits.__pltc0e
#define _int0e    __intc0.bits.__int0e
#define _int1e    __intc0.bits.__int1e
#define _pltc0f   __intc0.bits.__pltc0f
#define _int0f    __intc0.bits.__int0f
#define _int1f    __intc0.bits.__int1f
#define _sime     __intc1.bits.__sime
#define _lve      __intc1.bits.__lve
#define _mf0e     __intc1.bits.__mf0e
#define _mf1e     __intc1.bits.__mf1e
#define _simf     __intc1.bits.__simf
#define _lvf      __intc1.bits.__lvf
#define _mf0f     __intc1.bits.__mf0f
#define _mf1f     __intc1.bits.__mf1f
#define _mf2e     __intc2.bits.__mf2e
#define _tb0e     __intc2.bits.__tb0e
#define _tb1e     __intc2.bits.__tb1e
#define _pltc1e   __intc2.bits.__pltc1e
#define _mf2f     __intc2.bits.__mf2f
#define _tb0f     __intc2.bits.__tb0f
#define _tb1f     __intc2.bits.__tb1f
#define _pltc1f   __intc2.bits.__pltc1f
#define _mf3e     __intc3.bits.__mf3e
#define _mf4e     __intc3.bits.__mf4e
#define _mf5e     __intc3.bits.__mf5e
#define _mf3f     __intc3.bits.__mf3f
#define _mf4f     __intc3.bits.__mf4f
#define _mf5f     __intc3.bits.__mf5f
#define _ade      __mfi0.bits.__ade
#define _dee      __mfi0.bits.__dee
#define _adf      __mfi0.bits.__adf
#define _def      __mfi0.bits.__def
#define _ptm0pe   __mfi1.bits.__ptm0pe
#define _ptm0ae   __mfi1.bits.__ptm0ae
#define _ptm0pf   __mfi1.bits.__ptm0pf
#define _ptm0af   __mfi1.bits.__ptm0af
#define _stm0pe   __mfi2.bits.__stm0pe
#define _stm0ae   __mfi2.bits.__stm0ae
#define _stm0pf   __mfi2.bits.__stm0pf
#define _stm0af   __mfi2.bits.__stm0af
#define _stm1pe   __mfi3.bits.__stm1pe
#define _stm1ae   __mfi3.bits.__stm1ae
#define _ur0e     __mfi3.bits.__ur0e
#define _stm1pf   __mfi3.bits.__stm1pf
#define _stm1af   __mfi3.bits.__stm1af
#define _ur0f     __mfi3.bits.__ur0f
#define _ptm1pe   __mfi4.bits.__ptm1pe
#define _ptm1ae   __mfi4.bits.__ptm1ae
#define _ur1e     __mfi4.bits.__ur1e
#define _ptm1pf   __mfi4.bits.__ptm1pf
#define _ptm1af   __mfi4.bits.__ptm1af
#define _ur1f     __mfi4.bits.__ur1f
#define _ptm2pe   __mfi5.bits.__ptm2pe
#define _ptm2ae   __mfi5.bits.__ptm2ae
#define _ptm2pf   __mfi5.bits.__ptm2pf
#define _ptm2af   __mfi5.bits.__ptm2af
#define _vbgren   __vbgrc.bits.__vbgren
#define _ormc0    __ormc.bits.__ormc0
#define _ormc1    __ormc.bits.__ormc1
#define _ormc2    __ormc.bits.__ormc2
#define _ormc3    __ormc.bits.__ormc3
#define _ormc4    __ormc.bits.__ormc4
#define _ormc5    __ormc.bits.__ormc5
#define _ormc6    __ormc.bits.__ormc6
#define _ormc7    __ormc.bits.__ormc7
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _vbgen    __lvdc.bits.__vbgen
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _clksel0  __pscr.bits.__clksel0
#define _clksel1  __pscr.bits.__clksel1
#define _tb00     __tb0c.bits.__tb00
#define _tb01     __tb0c.bits.__tb01
#define _tb02     __tb0c.bits.__tb02
#define _tb0on    __tb0c.bits.__tb0on
#define _tb10     __tb1c.bits.__tb10
#define _tb11     __tb1c.bits.__tb11
#define _tb12     __tb1c.bits.__tb12
#define _tb1on    __tb1c.bits.__tb1on
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _sima0    __sima.bits.__sima0
#define _sima1    __sima.bits.__sima1
#define _sima2    __sima.bits.__sima2
#define _sima3    __sima.bits.__sima3
#define _sima4    __sima.bits.__sima4
#define _sima5    __sima.bits.__sima5
#define _sima6    __sima.bits.__sima6
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _txif0    __u0sr.bits.__txif0
#define _tidle0   __u0sr.bits.__tidle0
#define _rxif0    __u0sr.bits.__rxif0
#define _ridle0   __u0sr.bits.__ridle0
#define _oerr0    __u0sr.bits.__oerr0
#define _ferr0    __u0sr.bits.__ferr0
#define _nf0      __u0sr.bits.__nf0
#define _perr0    __u0sr.bits.__perr0
#define _tx80     __u0cr1.bits.__tx80
#define _rx80     __u0cr1.bits.__rx80
#define _txbrk0   __u0cr1.bits.__txbrk0
#define _stops0   __u0cr1.bits.__stops0
#define _prt0     __u0cr1.bits.__prt0
#define _pren0    __u0cr1.bits.__pren0
#define _bno0     __u0cr1.bits.__bno0
#define _uarten0  __u0cr1.bits.__uarten0
#define _teie0    __u0cr2.bits.__teie0
#define _tiie0    __u0cr2.bits.__tiie0
#define _rie0     __u0cr2.bits.__rie0
#define _wake0    __u0cr2.bits.__wake0
#define _adden0   __u0cr2.bits.__adden0
#define _brgh0    __u0cr2.bits.__brgh0
#define _rxen0    __u0cr2.bits.__rxen0
#define _txen0    __u0cr2.bits.__txen0
#define _swm0     __u0cr3.bits.__swm0
#define _st0rp0   __stm0c0.bits.__st0rp0
#define _st0rp1   __stm0c0.bits.__st0rp1
#define _st0rp2   __stm0c0.bits.__st0rp2
#define _st0on    __stm0c0.bits.__st0on
#define _st0ck0   __stm0c0.bits.__st0ck0
#define _st0ck1   __stm0c0.bits.__st0ck1
#define _st0ck2   __stm0c0.bits.__st0ck2
#define _st0pau   __stm0c0.bits.__st0pau
#define _st0cclr  __stm0c1.bits.__st0cclr
#define _st0dpx   __stm0c1.bits.__st0dpx
#define _st0pol   __stm0c1.bits.__st0pol
#define _st0oc    __stm0c1.bits.__st0oc
#define _st0io0   __stm0c1.bits.__st0io0
#define _st0io1   __stm0c1.bits.__st0io1
#define _st0m0    __stm0c1.bits.__st0m0
#define _st0m1    __stm0c1.bits.__st0m1
#define _pt0on    __ptm0c0.bits.__pt0on
#define _pt0ck0   __ptm0c0.bits.__pt0ck0
#define _pt0ck1   __ptm0c0.bits.__pt0ck1
#define _pt0ck2   __ptm0c0.bits.__pt0ck2
#define _pt0pau   __ptm0c0.bits.__pt0pau
#define _pt0cclr  __ptm0c1.bits.__pt0cclr
#define _pt0capts __ptm0c1.bits.__pt0capts
#define _pt0pol   __ptm0c1.bits.__pt0pol
#define _pt0oc    __ptm0c1.bits.__pt0oc
#define _pt0io0   __ptm0c1.bits.__pt0io0
#define _pt0io1   __ptm0c1.bits.__pt0io1
#define _pt0m0    __ptm0c1.bits.__pt0m0
#define _pt0m1    __ptm0c1.bits.__pt0m1
#define _pt0vlf   __ptm0c2.bits.__pt0vlf
#define _pt0tclr0 __ptm0c2.bits.__pt0tclr0
#define _pt0tclr1 __ptm0c2.bits.__pt0tclr1
#define _dacen    __dacc.bits.__dacen
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _clwb     __fc2.bits.__clwb
#define _fa0      __farl.bits.__fa0
#define _fa1      __farl.bits.__fa1
#define _fa2      __farl.bits.__fa2
#define _fa3      __farl.bits.__fa3
#define _fa4      __farl.bits.__fa4
#define _fa5      __farl.bits.__fa5
#define _fa6      __farl.bits.__fa6
#define _fa7      __farl.bits.__fa7
#define _fa8      __farh.bits.__fa8
#define _fa9      __farh.bits.__fa9
#define _fa10     __farh.bits.__fa10
#define _fa11     __farh.bits.__fa11
#define _fa12     __farh.bits.__fa12
#define _fa13     __farh.bits.__fa13
#define _st1rp0   __stm1c0.bits.__st1rp0
#define _st1rp1   __stm1c0.bits.__st1rp1
#define _st1rp2   __stm1c0.bits.__st1rp2
#define _st1on    __stm1c0.bits.__st1on
#define _st1ck0   __stm1c0.bits.__st1ck0
#define _st1ck1   __stm1c0.bits.__st1ck1
#define _st1ck2   __stm1c0.bits.__st1ck2
#define _st1pau   __stm1c0.bits.__st1pau
#define _st1cclr  __stm1c1.bits.__st1cclr
#define _st1dpx   __stm1c1.bits.__st1dpx
#define _st1pol   __stm1c1.bits.__st1pol
#define _st1oc    __stm1c1.bits.__st1oc
#define _st1io0   __stm1c1.bits.__st1io0
#define _st1io1   __stm1c1.bits.__st1io1
#define _st1m0    __stm1c1.bits.__st1m0
#define _st1m1    __stm1c1.bits.__st1m1
#define _pt1on    __ptm1c0.bits.__pt1on
#define _pt1ck0   __ptm1c0.bits.__pt1ck0
#define _pt1ck1   __ptm1c0.bits.__pt1ck1
#define _pt1ck2   __ptm1c0.bits.__pt1ck2
#define _pt1pau   __ptm1c0.bits.__pt1pau
#define _pt1cclr  __ptm1c1.bits.__pt1cclr
#define _pt1capts __ptm1c1.bits.__pt1capts
#define _pt1pol   __ptm1c1.bits.__pt1pol
#define _pt1oc    __ptm1c1.bits.__pt1oc
#define _pt1io0   __ptm1c1.bits.__pt1io0
#define _pt1io1   __ptm1c1.bits.__pt1io1
#define _pt1m0    __ptm1c1.bits.__pt1m0
#define _pt1m1    __ptm1c1.bits.__pt1m1
#define _pt2on    __ptm2c0.bits.__pt2on
#define _pt2ck0   __ptm2c0.bits.__pt2ck0
#define _pt2ck1   __ptm2c0.bits.__pt2ck1
#define _pt2ck2   __ptm2c0.bits.__pt2ck2
#define _pt2pau   __ptm2c0.bits.__pt2pau
#define _pt2cclr  __ptm2c1.bits.__pt2cclr
#define _pt2capts __ptm2c1.bits.__pt2capts
#define _pt2pol   __ptm2c1.bits.__pt2pol
#define _pt2oc    __ptm2c1.bits.__pt2oc
#define _pt2io0   __ptm2c1.bits.__pt2io0
#define _pt2io1   __ptm2c1.bits.__pt2io1
#define _pt2m0    __ptm2c1.bits.__pt2m0
#define _pt2m1    __ptm2c1.bits.__pt2m1
#define _sledc00  __sledc0.bits.__sledc00
#define _sledc01  __sledc0.bits.__sledc01
#define _sledc02  __sledc0.bits.__sledc02
#define _sledc03  __sledc0.bits.__sledc03
#define _sledc04  __sledc0.bits.__sledc04
#define _sledc05  __sledc0.bits.__sledc05
#define _sledc06  __sledc0.bits.__sledc06
#define _sledc07  __sledc0.bits.__sledc07
#define _sledc10  __sledc1.bits.__sledc10
#define _sledc11  __sledc1.bits.__sledc11
#define _sledc12  __sledc1.bits.__sledc12
#define _sledc13  __sledc1.bits.__sledc13
#define _sledc14  __sledc1.bits.__sledc14
#define _sledc15  __sledc1.bits.__sledc15
#define _pmps00   __pmps0.bits.__pmps00
#define _pmps01   __pmps0.bits.__pmps01
#define _pmps02   __pmps0.bits.__pmps02
#define _pmps03   __pmps0.bits.__pmps03
#define _pmps04   __pmps0.bits.__pmps04
#define _pmps05   __pmps0.bits.__pmps05
#define _pmps06   __pmps0.bits.__pmps06
#define _pmps07   __pmps0.bits.__pmps07
#define _pmps10   __pmps1.bits.__pmps10
#define _pmps11   __pmps1.bits.__pmps11
#define _pmps12   __pmps1.bits.__pmps12
#define _pmps13   __pmps1.bits.__pmps13
#define _pmps14   __pmps1.bits.__pmps14
#define _pmps15   __pmps1.bits.__pmps15
#define _txif1    __u1sr.bits.__txif1
#define _tidle1   __u1sr.bits.__tidle1
#define _rxif1    __u1sr.bits.__rxif1
#define _ridle1   __u1sr.bits.__ridle1
#define _oerr1    __u1sr.bits.__oerr1
#define _ferr1    __u1sr.bits.__ferr1
#define _nf1      __u1sr.bits.__nf1
#define _perr1    __u1sr.bits.__perr1
#define _tx81     __u1cr1.bits.__tx81
#define _rx81     __u1cr1.bits.__rx81
#define _txbrk1   __u1cr1.bits.__txbrk1
#define _stops1   __u1cr1.bits.__stops1
#define _prt1     __u1cr1.bits.__prt1
#define _pren1    __u1cr1.bits.__pren1
#define _bno1     __u1cr1.bits.__bno1
#define _uarten1  __u1cr1.bits.__uarten1
#define _teie1    __u1cr2.bits.__teie1
#define _tiie1    __u1cr2.bits.__tiie1
#define _rie1     __u1cr2.bits.__rie1
#define _wake1    __u1cr2.bits.__wake1
#define _adden1   __u1cr2.bits.__adden1
#define _brgh1    __u1cr2.bits.__brgh1
#define _rxen1    __u1cr2.bits.__rxen1
#define _txen1    __u1cr2.bits.__txen1
#define _swm1     __u1cr3.bits.__swm1
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren
#define _pas00    __pas0.bits.__pas00
#define _pas01    __pas0.bits.__pas01
#define _pas02    __pas0.bits.__pas02
#define _pas03    __pas0.bits.__pas03
#define _pas04    __pas0.bits.__pas04
#define _pas05    __pas0.bits.__pas05
#define _pas06    __pas0.bits.__pas06
#define _pas07    __pas0.bits.__pas07
#define _pas10    __pas1.bits.__pas10
#define _pas11    __pas1.bits.__pas11
#define _pas12    __pas1.bits.__pas12
#define _pas13    __pas1.bits.__pas13
#define _pas14    __pas1.bits.__pas14
#define _pas15    __pas1.bits.__pas15
#define _pas16    __pas1.bits.__pas16
#define _pas17    __pas1.bits.__pas17
#define _pbs00    __pbs0.bits.__pbs00
#define _pbs01    __pbs0.bits.__pbs01
#define _pbs02    __pbs0.bits.__pbs02
#define _pbs03    __pbs0.bits.__pbs03
#define _pbs04    __pbs0.bits.__pbs04
#define _pbs05    __pbs0.bits.__pbs05
#define _pbs06    __pbs0.bits.__pbs06
#define _pbs07    __pbs0.bits.__pbs07
#define _pbs10    __pbs1.bits.__pbs10
#define _pbs11    __pbs1.bits.__pbs11
#define _pbs12    __pbs1.bits.__pbs12
#define _pbs13    __pbs1.bits.__pbs13
#define _pbs14    __pbs1.bits.__pbs14
#define _pbs15    __pbs1.bits.__pbs15
#define _pbs16    __pbs1.bits.__pbs16
#define _pbs17    __pbs1.bits.__pbs17
#define _pcs00    __pcs0.bits.__pcs00
#define _pcs01    __pcs0.bits.__pcs01
#define _pcs02    __pcs0.bits.__pcs02
#define _pcs03    __pcs0.bits.__pcs03
#define _pcs04    __pcs0.bits.__pcs04
#define _pcs05    __pcs0.bits.__pcs05
#define _pcs06    __pcs0.bits.__pcs06
#define _pcs07    __pcs0.bits.__pcs07
#define _pcs10    __pcs1.bits.__pcs10
#define _pcs11    __pcs1.bits.__pcs11
#define _pcs12    __pcs1.bits.__pcs12
#define _pcs13    __pcs1.bits.__pcs13
#define _pds00    __pds0.bits.__pds00
#define _pds01    __pds0.bits.__pds01
#define _pds02    __pds0.bits.__pds02
#define _pds03    __pds0.bits.__pds03
#define _pds04    __pds0.bits.__pds04
#define _pds05    __pds0.bits.__pds05
#define _pds06    __pds0.bits.__pds06
#define _pds07    __pds0.bits.__pds07
#define _ifs00    __ifs0.bits.__ifs00
#define _ifs01    __ifs0.bits.__ifs01
#define _ifs02    __ifs0.bits.__ifs02
#define _ifs03    __ifs0.bits.__ifs03
#define _ifs04    __ifs0.bits.__ifs04
#define _ifs05    __ifs0.bits.__ifs05
#define _ifs06    __ifs0.bits.__ifs06
#define _ifs07    __ifs0.bits.__ifs07
#define _ifs10    __ifs1.bits.__ifs10
#define _ifs11    __ifs1.bits.__ifs11
#define _ifs12    __ifs1.bits.__ifs12
#define _ifs13    __ifs1.bits.__ifs13
#define _ifs14    __ifs1.bits.__ifs14
#define _ifs15    __ifs1.bits.__ifs15

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _BA45F5260_H_
