#ifndef __SPEAK_H__
#define __SPEAK_H__
#ifdef SUPPORT_SPEAK_FUNCTION
#define CMD_SPEAKER_TEST				0x00
#define CMD_WELCOME_HELLO				0x01
#define CMD_LOCATION_SET_GUIDE			0x02
#define CMD_TEST_OPERATION_GUIDE		0x03
#define CMD_LOCATION_NOT_SET			0x04
#define CMD_LOCATION_CHANGE				0x05
#define CMD_LOCATION_SELECT_NEXT		0x06

#define CMD_LOCATION_ENTRYWAY			0X07
#define CMD_LOCATION_BASEMENT			0X08
#define CMD_LOCATION_LIVING_ROOM		0X09
#define CMD_LOCATION_DINING_ROOM		0X0A
#define CMD_LOCATION_KITCHEN			0X0B
#define CMD_LOCATION_HALLWAY			0X0C
#define CMD_LOCATION_MASTER_BEDROOM		0X0D
#define CMD_LOCATION_KIDS_ROOM			0X0E
#define CMD_LOCATION_GUEST_ROOM			0X0F
#define CMD_LOCATION_DEN				0X10
#define CMD_LOCATION_FAMILY_ROOM		0X11
#define CMD_LOCATION_STUDY				0X12
#define CMD_LOCATION_OFFICE				0X13
#define CMD_LOCATION_WORKSHOP			0X14
#define CMD_LOCATION_UTILITY_ROOM		0X15
#define CMD_LOCATION_ATTIC				0X16
#define CMD_NO_LOCATION					0X17

#define CMD_LOCATION_SAVED				0X18
#define CMD_UNABLE_SET_LOCATION			0X19
#define CMD_SEARCHING_DEVICE			0X1A
#define CMD_READ_TO_CONNECT				0X1B
#define CMD_CONNECT_SUCCESS				0X1C
#define CMD_CONNECT_FAILED				0X1D
#define CMD_DISCONNECTED				0X1E

#define CMD_TEST_REMIND					0X1F
#define CMD_TEST_SMOKE					0X20
#define CMD_TEST_CO						0X21
#define CMD_TEST_FINISHED				0X22
#define CMD_TEST_CANCELLED				0X23
#define CMD_NORMAL_WORKING_STATUS		0X24

#define CMD_SMOKE_SENSOR_ERR			0X25
#define CMD_CO_SENSOR_ERR				0X26
#define CMD_REPLACE_DEV_LOW_BAT			0X27
#define CMD_REPLACE_BAT_LOW_BAT			0X28
#define CMD_WARNING						0X29
#define CMD_SMOKE_DETECTED				0X2A
#define CMD_IN							0X2B
#define CMD_EVACUATE					0X2C

#define CMD_CO_ALARM_IN					0X2D
#define CMD_CO_ALARM_MOVE_TO_OUTSIDE	0X2E
#define CMD_CO_ALARM_NO_LOCATION		0X2F

#define CMD_SMOKE_ALARM_MUTED			0X30
#define CMD_CO_ALARM_MUTED				0X31
#define CMD_SMOKE_ALARM_CANNOT_MUTED	0X32
#define CMD_CO_ALARM_CANNOT_MUTED		0X33
#define CMD_CANCEL_ALARM				0X34
#define CMD_SMOKE_ALARM_HISTORY_REMIND	0X35
#define CMD_CO_ALARM_HISTORY_REMIND		0X36
#define CMD_END_LIFE					0X37
#define CMD_ENTRY_MUTE_MODE				0X38
#define CMD_INSTALL_BATTERY				0X39

#define CMD_MUSIC_STOP					0XF0
#define CMD_MUSIC_VOLUME_1				0XF1
#define CMD_MUSIC_VOLUME_2				0XF2
#define CMD_MUSIC_VOLUME_3				0XF3
#define CMD_MUSIC_VOLUME_4				0XF4
#define CMD_MUSIC_VOLUME_5				0XF5
#define CMD_MUSIC_VOLUME_6				0XF6
#define CMD_MUSIC_VOLUME_7				0XF7
#define CMD_MUSIC_VOLUME_8				0XF8
#define CMD_MUSIC_VOLUME_9				0XF9
#define CMD_MUSIC_VOLUME_10				0XFA
#define CMD_MUSIC_VOLUME_11				0XFB
#define CMD_MUSIC_VOLUME_12				0XFC
#define CMD_MUSIC_VOLUME_13				0XFD
#define CMD_MUSIC_VOLUME_14				0XFE
#define CMD_MUSIC_VOLUME_15				0XFF

#define CMD_MUSIC_VOLUME_ADD			0XE9
#define CMD_MUSIC_VOLUME_REDUCE			0XEA
#define CMD_MUSIC_MUTE					0XEB
#define CMD_MUSIC_REPEAT				0XEC
#define CMD_MUSIC_PRE					0XED
#define CMD_MUSIC_NEXT					0XEE
#define CMD_MUSIC_LOOP					0XEF


#define EnableVoiceVcc()	{SPEAK_VCC_EN_PIN = 0;}
#define DisableVoiceVcc()	{SPEAK_VCC_EN_PIN = 1;}

void SpeakerInit(void);
void SpeakerSendCmdForPowerOn(uint8_t VoiceData);
void SpeakerSendCmd(uint32_t VoiceData);
#endif
#endif


